test:1.61:
  script: &test_script
  - &print_version rustc --version && cargo --version
  - cargo test --all --verbose
  - cargo test --all --all-features --verbose
  image: rust:1.61

test:stable:
  script: *test_script
  image: rust

test:nightly:
  script: *test_script
  image: rustlang/rust:nightly

clippy:
  script:
  - *print_version
  - rustup component add clippy-preview
  - cargo clippy --verbose
  image: rust

rustfmt:
  script:
  - *print_version
  - rustup component add rustfmt-preview
  - cargo fmt -- --check
  image: rust
